// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btempndowvtalgligddc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZW1wbmRvd3Z0YWxnbGlnZGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0NTc2NjgsImV4cCI6MjA3NTAzMzY2OH0.5bcJvvy8uMn-sXs_8bw_RLyapnx9yhClHvn2f6A_LJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});